name: spp ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]
    name: spp build ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install deps
        run: |
          gem install bundler:2.1.2
          bundle install --jobs 4 --retry 3
      - name: lint
        run: bundle exec rubocop --parallel
      - name: test
        run: bundle exec rspec
